name: 'SSH Known Hosts Action'
description: 'Adds entries to the known_hosts file'
author: 'TrueMark'
branding:
  icon: 'check-circle'
  color: 'red'
inputs:
  entries:
    required: false
    description: 'Entries to add to the known_hosts file'
  scan-hosts:
    required: false
    description: 'Hosts to scan for SSH keys'
runs:
  using: 'node16'
  main: 'dist/index.js'
